name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      # - name: Show available simulators
      #   run: xcrun simctl list devices
      - name: Detect available simulator
        run: |
          sim=$(xcrun simctl list devices available | grep "iPhone 14 (" | grep -oE '[A-F0-9-]{36}' | head -n1)
          echo $sim | cat >sim
          echo Using simulator: $sim
      - name: Run tests
        run: |
          xcodebuild test \
            -workspace MyWaySwiftUI.xcworkspace \
            -scheme {{ $default }} \
            -destination {{ $sim }}
