name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  run: echo ${{ github.workflow }} ${{ github.ref }}

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Detect available schemes and set as variable
      # - name: Set Default Scheme
      #   run: |
      #     scheme_list=$(xcodebuild -list -json | tr -d "\n")
      #     scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
      #     echo $scheme | cat >scheme
      #     echo Using scheme: $scheme
      
      - name: Testing iOS app
        run: |
          xcodebuild -scheme MyWaySwiftUI \
              -destination platform=iOS\ Simulator,OS=18.2,name=iPhone\ 16 \
              clean test | xcpretty
